GET http://localhost:7071/api/HttpTrigger

###

POST http://localhost:7071/api/HttpTrigger
Content-Type: application/json

{
    "name": "John Doe"
}

###

GET https://functionapp20220913.azurewebsites.net/api/httptrigger

###

POST https://functionapp20220913.azurewebsites.net/api/httptrigger
Content-Type: application/json

{
    "name": "John Doe"
}
